In [1]:
import numpy as np 
from numpy import linalg as LA

#### Question - 1 (i)

In [127]:
def DiagDom(A):
    diag_coeff = np.diag(np.abs(A)) 
    row_sum = np.sum(np.abs(A), axis=1) - diag_coeff 
    if np.all(diag_coeff > row_sum):
        print("\nMatrix is Diagonally Dominant")
    else:
        print("\nNOT Diagonally Dominant")
    return
A = np.random.randint(-10,10, size=(4, 4))
print(A)
DiagDom(A)

[[  1   6 -10  -2]
 [ -2   2   0  -8]
 [  6   8   0  -8]
 [  1   3   4   6]]

NOT Diagonally Dominant


#### Question - 1 (ii)

In [128]:
def gauss_seidal(A, b, n):
    print("System of equations:\n") 
    for i in range(A.shape[0]):     
        row = ["{0:3g}*x{1}".format(A[i, j], j + 1) for j in range(A.shape[1])]     
        print("[{0}] = [{1:3g}]".format(" + ".join(row), b[i])) 
        x = np.zeros_like(b) 

    print("\nIterations:\n")

    for it_count in range(0, n):     
        x_new = np.zeros_like(x) 
        print("Iteration {0}: {1}".format(it_count, x))
        print("1 Norm",np.linalg.norm(x, ord=1))
        print("Inf Norm: ",LA.norm(x, np.inf))
        print("Frobenius Norm",np.linalg.norm(x, ord=2))

        for i in range(A.shape[0]):         
            s1 = np.dot(A[i, :i], x_new[:i])         
            s2 = np.dot(A[i, i + 1:], x[i + 1:])         
            x_new[i] = (b[i] - s1 - s2) / A[i, i]     
            if np.allclose(x, x_new, rtol=1e-8):         
                break     
        x = x_new 

    print("\nSolution: {0}".format(x)) 
    error = np.dot(A, x) - b 
    print("\nError: {0}".format(error)) 

In [129]:
n = 5
# initialize the matrix 
#A = np.random.randint(min_val,max_val,(<num_rows>,<num_cols>))
A = np.random.randint(1,5, size=(4, 4))
# initialize the RHS vector 
b = np.round(np.random.uniform(1, 5, 4), 0)
gauss_seidal(A, b, n)

System of equations:

[  4*x1 +   3*x2 +   4*x3 +   3*x4] = [  4]
[  3*x1 +   2*x2 +   2*x3 +   2*x4] = [  4]
[  1*x1 +   4*x2 +   3*x3 +   2*x4] = [  2]
[  1*x1 +   1*x2 +   2*x3 +   1*x4] = [  3]

Iterations:

Iteration 0: [0. 0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [ 1.          0.5        -0.33333333  2.16666667]
1 Norm 4.0
Inf Norm:  2.1666666666666665
Frobenius Norm 2.4608038433722332
Iteration 2: [-0.66666667  1.16666667 -2.11111111  6.72222222]
1 Norm 10.666666666666668
Inf Norm:  6.722222222222222
Frobenius Norm 7.172908565146402
Iteration 3: [-2.80555556  1.59722222 -5.00925926 14.22685185]
1 Norm 23.638888888888893
Inf Norm:  14.226851851851853
Frobenius Norm 15.424598949194248
Iteration 4: [-5.8587963   1.57060185 -8.95910494 25.20640432]
1 Norm 41.59490740740741
Inf Norm:  25.20640432098766
Frobenius Norm 27.430287353700905

Solution: [-10.12364969   0.93817515 -14.01395319  40.21338092]

Error: [22.90425669 19.90425669 30.01395319  0.        ]


#### Question - 1 (iii)

In [130]:
def gauss_jacobi(A,b, n):
    # prints the system
    print("System of equations:\n") 
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{0}] = [{1:3g}]".format(" + ".join(row), b[i])) 
    print("\nIterations:\n")
    x = np.zeros_like(b)
    for it_count in range(n):
        print("Iteration {0}: {1}".format(it_count, x))
        print("1 Norm",np.linalg.norm(x, ord=1))
        print("Inf Norm: ",LA.norm(x, np.inf))
        print("Frobenius Norm",np.linalg.norm(x, ord=2))
        x_new = np.zeros_like(x)

        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]

        if np.allclose(x, x_new, atol=1e-10, rtol=0.):
            break

        x = x_new

    print("\nSolution: {0}".format(x)) 
    error = np.dot(A, x) - b
    print("\nError: {0}".format(error))    

In [131]:
n = 5
# initialize the matrix
A = np.random.randint(1,10, size=(4, 4))
# initialize the RHS vector
b = np.round(np.random.uniform(1, 5, 4), 0)
gauss_jacobi(A, b, n)

System of equations:

[6*x1 + 1*x2 + 3*x3 + 1*x4] = [  4]
[5*x1 + 1*x2 + 2*x3 + 2*x4] = [  4]
[5*x1 + 1*x2 + 1*x3 + 1*x4] = [  4]
[8*x1 + 7*x2 + 3*x3 + 1*x4] = [  5]

Iterations:

Iteration 0: [0. 0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [0.66666667 4.         4.         5.        ]
1 Norm 13.666666666666668
Inf Norm:  5.0
Frobenius Norm 7.579211333934715
Iteration 2: [ -2.83333333 -17.33333333  -8.33333333 -40.33333333]
1 Norm 68.83333333333333
Inf Norm:  40.333333333333336
Frobenius Norm 44.77381427178664
Iteration 3: [ 14.44444444 115.5         75.83333333 174.        ]
1 Norm 379.7777777777778
Inf Norm:  174.0
Frobenius Norm 222.65575766135734
Iteration 4: [  -85.5         -567.88888889  -357.72222222 -1146.55555556]
1 Norm 2157.666666666667
Inf Norm:  1146.5555555555557
Frobenius Norm 1331.3011944599052

Solution: [ 465.26851852 3440.05555556 2145.94444444 5737.38888889]

Error: [18402.88888889 21529.06481481 13645.73148148 39972.75925926]


#### Question - 1 (iv)

In [132]:
def DiagDom(A):
    diag_coeff = np.diag(np.abs(A)) 
    row_sum = np.sum(np.abs(A), axis=1) - diag_coeff 
    if np.all(diag_coeff > row_sum):
        print("Matrix is Diagonally Dominant\n")
    else:
        print("NOT Diagonally Dominant\n")
    return
n = 100
A = np.array([[4., -1., -1., 1.],[-2.,6.,1.,1.],[-1.,1.,7.,1.], [1.,0.,0.,2.]]) # Making A as static so that it becomes diagonally dominant
b = np.round(np.random.uniform(1, 5, 4), 0) # B can be randomly initialised
DiagDom(A)
gauss_seidal(A,b,n)

Matrix is Diagonally Dominant

System of equations:

[  4*x1 +  -1*x2 +  -1*x3 +   1*x4] = [  3]
[ -2*x1 +   6*x2 +   1*x3 +   1*x4] = [  4]
[ -1*x1 +   1*x2 +   7*x3 +   1*x4] = [  4]
[  1*x1 +   0*x2 +   0*x3 +   2*x4] = [  2]

Iterations:

Iteration 0: [0. 0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [0.75       0.91666667 0.54761905 0.625     ]
1 Norm 2.8392857142857144
Inf Norm:  0.9166666666666666
Frobenius Norm 1.4468204446623536
Iteration 2: [0.95982143 0.79117063 0.50623583 0.52008929]
1 Norm 2.7773171768707483
Inf Norm:  0.9598214285714286
Frobenius Norm 1.4401304547267495
Iteration 3: [0.94432929 0.81038891 0.51626444 0.52783535]
1 Norm 2.7988180019031423
Inf Norm:  0.9443292942176871
Frobenius Norm 1.4469371581258603
Iteration 4: [0.9497045  0.8092182  0.51609299 0.52514775]
1 Norm 2.8001634435750633
Inf Norm:  0.9497045004757856
Frobenius Norm 1.4487597698899042
Iteration 5: [0.95004086 0.80980683 0.5164409  0.52497957]
1 Norm 2.801268157701527
Inf N

In [133]:
def DiagDom(A):
    diag_coeff = np.diag(np.abs(A)) 
    row_sum = np.sum(np.abs(A), axis=1) - diag_coeff 
    if np.all(diag_coeff > row_sum):
        print("Matrix is Diagonally Dominant\n")
    else:
        print("NOT Diagonally Dominant\n")
    return
n = 100
A = np.random.randint(1,10, size=(4, 4))
b = np.round(np.random.uniform(1, 5, 4), 0) # B can be randomly initialised
DiagDom(A)
gauss_seidal(A,b, n)

NOT Diagonally Dominant

System of equations:

[  2*x1 +   4*x2 +   8*x3 +   1*x4] = [  1]
[  1*x1 +   6*x2 +   1*x3 +   3*x4] = [  2]
[  1*x1 +   7*x2 +   9*x3 +   1*x4] = [  4]
[  9*x1 +   6*x2 +   2*x3 +   8*x4] = [  4]

Iterations:

Iteration 0: [0. 0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [ 0.5         0.25        0.19444444 -0.29861111]
1 Norm 1.2430555555555556
Inf Norm:  0.5
Frobenius Norm 0.6629307940157261
Iteration 2: [-0.62847222  0.55497685  0.11580504  0.76184735]
1 Norm 2.0611014660493825
Inf Norm:  0.7618473508230451
Frobenius Norm 1.1387707555556124
Iteration 3: [-1.45409754  0.17545841  0.38489348  1.90804256]
1 Norm 3.9224919937057043
Inf Norm:  1.908042560025625
Frobenius Norm 2.435971002039489
Iteration 4: [-2.34451202 -0.29408486  0.72167372  3.17772124]
1 Norm 6.537991836078323
Inf Norm:  3.1777212389541827
Frobenius Norm 4.025164314227061
Iteration 5: [-3.38738578 -0.81124194  1.09870646  4.64456384]
1 Norm 9.941898020865837
Inf Norm: 

#### Question - 1 (v)

In [134]:
def DiagDom(A):
    diag_coeff = np.diag(np.abs(A)) 
    row_sum = np.sum(np.abs(A), axis=1) - diag_coeff 
    if np.all(diag_coeff > row_sum):
        print("Matrix is Diagonally Dominant\n")
    else:
        print("NOT Diagonally Dominant\n")
    return
n = 100
A = np.array([[4., -1., -1., 1.],[-2.,6.,1.,1.],[-1.,1.,7.,1.], [1.,0.,0.,2.]]) # Making A as static so that it becomes diagonally dominant
b = np.round(np.random.uniform(1, 5, 4), 0) # B can be randomly initialised
DiagDom(A)
gauss_jacobi(A,b,n)

Matrix is Diagonally Dominant

System of equations:

[4.0*x1 + -1.0*x2 + -1.0*x3 + 1.0*x4] = [  2]
[-2.0*x1 + 6.0*x2 + 1.0*x3 + 1.0*x4] = [  4]
[-1.0*x1 + 1.0*x2 + 7.0*x3 + 1.0*x4] = [  1]
[1.0*x1 + 0.0*x2 + 0.0*x3 + 2.0*x4] = [  5]

Iterations:

Iteration 0: [0. 0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [0.5        0.66666667 0.14285714 2.5       ]
1 Norm 3.8095238095238093
Inf Norm:  2.5
Frobenius Norm 2.639100719508399
Iteration 2: [ 0.07738095  0.39285714 -0.23809524  2.25      ]
1 Norm 2.958333333333333
Inf Norm:  2.25
Frobenius Norm 2.2977192798270396
Iteration 3: [-0.02380952  0.35714286 -0.22363946  2.46130952]
1 Norm 3.065901360544218
Inf Norm:  2.4613095238095237
Frobenius Norm 2.497233888127076
Iteration 4: [-0.08195153  0.28578515 -0.26318027  2.51190476]
1 Norm 3.1428217120181405
Inf Norm:  2.511904761904762
Frobenius Norm 2.543092328710624
Iteration 5: [-0.12232497  0.26456207 -0.26852021  2.54097577]
1 Norm 3.1963830174927113
Inf Norm:  2.540975

In [135]:
def DiagDom(A):
    diag_coeff = np.diag(np.abs(A)) 
    row_sum = np.sum(np.abs(A), axis=1) - diag_coeff 
    if np.all(diag_coeff > row_sum):
        print("Matrix is Diagonally Dominant\n")
    else:
        print("NOT Diagonally Dominant\n")
    return
n = 100
A = np.random.randint(1,10, size=(4, 4))
b = np.round(np.random.uniform(1, 5, 4), 0) # B can be randomly initialised
DiagDom(A)
gauss_jacobi(A,b,n)

NOT Diagonally Dominant

System of equations:

[7*x1 + 5*x2 + 7*x3 + 4*x4] = [  2]
[1*x1 + 9*x2 + 5*x3 + 9*x4] = [  5]
[3*x1 + 2*x2 + 7*x3 + 8*x4] = [  4]
[3*x1 + 8*x2 + 7*x3 + 9*x4] = [  5]

Iterations:

Iteration 0: [0. 0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [0.28571429 0.55555556 0.57142857 0.55555556]
1 Norm 1.9682539682539681
Inf Norm:  0.5714285714285714
Frobenius Norm 1.0126436766816878
Iteration 2: [-1.         -0.34920635 -0.3446712  -0.47795414]
1 Norm 2.1718316956412194
Inf Norm:  1.0
Frobenius Norm 1.2120987897222675
Iteration 3: [1.15293525 1.33610481 1.64600655 1.46737213]
1 Norm 5.602418745275887
Inf Norm:  1.6460065507684551
Frobenius Norm 2.824350244011073
Iteration 4: [-3.15315121 -1.95436858 -1.98142749 -2.29663223]
1 Norm 9.38557951105192
Inf Norm:  3.153151207572976
Frobenius Norm 4.791919615159327
Iteration 5: [4.97548061 4.30333097 5.10589266 4.88493274]
1 Norm 19.269636990785415
Inf Norm:  5.105892663607812
Frobenius Norm 9.654365466

#### QC Example -

In [136]:
# Gauss Seidal - Q1. (ii)
import numpy as np 
from numpy import linalg as LA

ITERATION_LIMIT = 5 
# initialize the matrix 

A = np.array([[4., -1., -1,],[-2.,6.,1.],[-1.,1.,7.]])
# initialize the RHS vector 
b = np.array([3., 9., -6.]) 
print("System of equations:\n") 

for i in range(A.shape[0]):     
    row = ["{0:3g}*x{1}".format(A[i, j], j + 1) for j in range(A.shape[1])]     
    print("[{0}] = [{1:3g}]".format(" + ".join(row), b[i])) 
    x = np.zeros_like(b) 
    
print("\nIterations:\n")

for it_count in range(0, ITERATION_LIMIT):     
    x_new = np.zeros_like(x) 
    print("Iteration {0}: {1}".format(it_count, x))
    print("1 Norm",np.linalg.norm(x, ord=1))
    print("Inf Norm: ",LA.norm(x, np.inf))
    print("Frobenius Norm",np.linalg.norm(x, ord=2))
    
    for i in range(A.shape[0]):         
        s1 = np.dot(A[i, :i], x_new[:i])         
        s2 = np.dot(A[i, i + 1:], x[i + 1:])         
        x_new[i] = (b[i] - s1 - s2) / A[i, i] 
        
        if np.allclose(x, x_new, rtol=1e-8):         
            break     
    x = x_new 
    
print("\nSolution: {0}".format(x)) 
error = np.dot(A, x) - b 
print("\nError: {0}".format(error)) 

System of equations:

[  4*x1 +  -1*x2 +  -1*x3] = [  3]
[ -2*x1 +   6*x2 +   1*x3] = [  9]
[ -1*x1 +   1*x2 +   7*x3] = [ -6]

Iterations:

Iteration 0: [0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [ 0.75  1.75 -1.  ]
1 Norm 3.5
Inf Norm:  1.75
Frobenius Norm 2.1505813167606567
Iteration 2: [ 0.9375      1.97916667 -1.00595238]
1 Norm 3.922619047619048
Inf Norm:  1.9791666666666667
Frobenius Norm 2.4099682855150206
Iteration 3: [ 0.99330357  1.99875992 -1.00077948]
1 Norm 3.992842970521542
Inf Norm:  1.9987599206349207
Frobenius Norm 2.446068839965882
Iteration 4: [ 0.99949511  1.99996162 -1.00006664]
1 Norm 3.999523370856279
Inf Norm:  1.999961616591081
Frobenius Norm 2.4492795340105125

Solution: [ 0.99997374  2.00000236 -1.00000409]

Error: [-1.03294755e-04  6.25563198e-05  0.00000000e+00]


In [137]:
#Gauss Jacobi - Q1 (iii)
import numpy as np
ITERATION_LIMIT = 3
# initialize the matrix
A = np.array([[4., 2., -2.],
              [1., -3., -1.],
              [3., -1., 4.]])
# initialize the RHS vector
b = np.array([0., 7., 5.])

# prints the system
print("System of equations:\n")
for i in range(A.shape[0]):
    row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
    print(" + ".join(row), "=", b[i])
print()

x = np.zeros_like(b)
for it_count in range(ITERATION_LIMIT):
    print("Iteration {0}: {1}".format(it_count, x))
    print("1 Norm",np.linalg.norm(x, ord=1))
    print("Inf Norm: ",LA.norm(x, np.inf))
    print("Frobenius Norm",np.linalg.norm(x, ord=2))
    x_new = np.zeros_like(x)

    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x[:i])
        s2 = np.dot(A[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]

    if np.allclose(x, x_new, atol=1e-10, rtol=0.):
        break

    x = x_new

print("Solution:")
print(x)
error = np.dot(A, x) - b
print("Error:")
print(error) 

System of equations:

4.0*x1 + 2.0*x2 + -2.0*x3 = 0.0
1.0*x1 + -3.0*x2 + -1.0*x3 = 7.0
3.0*x1 + -1.0*x2 + 4.0*x3 = 5.0

Iteration 0: [0. 0. 0.]
1 Norm 0.0
Inf Norm:  0.0
Frobenius Norm 0.0
Iteration 1: [ 0.         -2.33333333  1.25      ]
1 Norm 3.5833333333333335
Inf Norm:  2.3333333333333335
Frobenius Norm 2.647063362378099
Iteration 2: [ 1.79166667 -2.75        0.66666667]
1 Norm 5.208333333333334
Inf Norm:  2.75
Frobenius Norm 3.349181077351431
Solution:
[ 1.70833333 -1.95833333 -0.78125   ]
Error:
[ 4.47916667  1.36458333 -1.04166667]
